export const primaryTopics = [
  'Cody Free',
  'Cody Pro',
  'Cod Enterprise',
  'Model (LLM)',
  'Autocomplete',
  'Chat',
  'Commands',
  'Code Search',
  'Batch Changes',
  'Code Monitoring',
  'Code ownership',
  'Code Insights',
  'Notebooks',
  'Web',
  'VS Code',
  'Jetbrains',
  'Neovim',
  'Public',
  'Cloud',
  'Admin',
  'Sourcegraph CLI',
  'GraphQL API',
  'Streaming API'
]

export const secondaryTopics = [
  'Integration',
  'Security',
  'Scalability',
  'Performance',
  'Customization',
  'Collaboration',
  'Documentation',
  'Support',
  'Community',
  'Updates',
  'Case Studies',
  'Dashboards',
  'Automation',
  'Vulnerability Fix',
  'Search Speed',
  'Developer Velocity'
]
