name: Accessibility issue
description: Create an issue that is automatically attached to the WCAG 2.1 AA Tracking Issue
title: '[Accessibility]: '
labels:
  - 'accessibility'
  - 'wcag/2.1'
  - 'wcag/2.1/fixing'
  - 'team/content-platform'
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your contribution to the accessibility of Sourcegraph!
  - type: dropdown
    id: audit-type
    attributes:
      label: Audit type
      description: What type of audit does this issue relate to?
      options:
        - Keyboard navigation
        - Screen reader navigation
        - Mobile device navigation
        - ARC Toolkit
        - General/Other
    validations:
      required: true
  - type: input
    id: user-journey-issue
    attributes:
      label: User journey audit issue
      description: If this issue is related to a specific GH issue for auditing an individual user journey, please provide a link to the issue here.
  - type: textarea
    id: problem-description
    attributes:
      label: Problem description
      description: Please describe the issue and the steps required to replicate it.
    validations:
      required: true
  - type: textarea
    id: solution-description
    attributes:
      label: Expected behavior
      description: Please describe the expected or accessibility-compliant behavior.
    validations:
      required: true
  - type: textarea
    id: additional-details
    attributes:
      label: Additional details
      description: Provide any notes, screenshots, and/or additional context here.
    validations:
      required: false
