export interface ComparisonFeature {
    feature: string
    feature_details: string
    view_feature_details: boolean
    cody: boolean | string
    cody_details: string | string[]
    view_cody_details: boolean
    competitor: boolean | string
    competitor_details: string | string[]
    view_competitor_details: boolean
}

export interface CompareDataType {
    competitorName: string
    featureSupport: ComparisonFeature[]
    ideSupport: ComparisonFeature[]
    llmSupport: ComparisonFeature[]
    contextSupport: ComparisonFeature[]
    pricingSupport: ComparisonFeature[]
}

export const copilotVsCody: CompareDataType = {
    competitorName: 'GitHub Copilot',
    featureSupport: [
        {
            feature: 'Autocomplete',
            feature_details: '',
            view_feature_details: false,
            cody: true,
            cody_details: '',
            view_cody_details: false,
            competitor: true,
            competitor_details: '',
            view_competitor_details: false,
        },
        {
            feature: 'Chat',
            feature_details: '',
            view_feature_details: false,
            cody: true,
            cody_details: '',
            view_cody_details: false,
            competitor: true,
            competitor_details: '',
            view_competitor_details: false,
        },
        {
            feature: 'Commands',
            feature_details: '',
            view_feature_details: false,
            cody: true,
            cody_details: '',
            view_cody_details: false,
            competitor: true,
            competitor_details: '',
            view_competitor_details: false,
        },
        {
            feature: 'Custom commands',
            feature_details: '',
            view_feature_details: false,
            cody: true,
            cody_details: '',
            view_cody_details: false,
            competitor: false,
            competitor_details: '',
            view_competitor_details: false,
        },
    ],
    ideSupport: [
        {
            feature: 'Visual Studio Code',
            feature_details: '',
            view_feature_details: false,
            cody: true,
            cody_details: '',
            view_cody_details: false,
            competitor: true,
            competitor_details: '',
            view_competitor_details: false,
        },
        {
            feature: 'JetBrains',
            feature_details: '',
            view_feature_details: false,
            cody: true,
            cody_details: '',
            view_cody_details: false,
            competitor: true,
            competitor_details: '',
            view_competitor_details: false,
        },
        {
            feature: 'Visual Studio',
            feature_details: '',
            view_feature_details: false,
            cody: false,
            cody_details: '',
            view_cody_details: false,
            competitor: true,
            competitor_details: '',
            view_competitor_details: false,
        },
        {
            feature: 'Other',
            feature_details: '',
            view_feature_details: false,
            cody: true,
            cody_details: ['Neovim.'],
            view_cody_details: false,
            competitor: true,
            competitor_details: ['Neovim.'],
            view_competitor_details: false,
        },
    ],
    llmSupport: [
        {
            feature: 'Chat model (default)',
            feature_details: '',
            view_feature_details: false,
            cody: 'Claude 3',
            cody_details: '',
            view_cody_details: false,
            competitor: 'GPT-4',
            competitor_details: '',
            view_competitor_details: false,
        },
        {
            feature: 'Autocomplete model (default)',
            feature_details: '',
            view_feature_details: false,
            cody: 'StarCoder',
            cody_details: '',
            view_cody_details: false,
            competitor: 'Codex',
            competitor_details: '',
            view_competitor_details: false,
        },
        {
            feature: 'Choose your LLM',
            feature_details: '',
            view_feature_details: false,
            cody: true,
            cody_details: '',
            view_cody_details: false,
            competitor: false,
            competitor_details: '',
            view_competitor_details: false,
        },
        {
            feature: 'Bring your own LLM key',
            feature_details: '',
            view_feature_details: false,
            cody: true,
            cody_details: '',
            view_cody_details: false,
            competitor: false,
            competitor_details: '',
            view_competitor_details: false,
        },
        {
            feature: 'LLM hosting',
            feature_details: '',
            view_feature_details: false,
            cody: 'Cloud',
            cody_details: '',
            view_cody_details: false,
            competitor: 'Cloud',
            competitor_details: '',
            view_competitor_details: false,
        },
    ],
    contextSupport: [
        {
            feature: 'Personalized responses using codebase context',
            feature_details: '',
            view_feature_details: false,
            cody: true,
            cody_details: 'Available on all tiers. Enterprise tier supports all code hosts.',
            view_cody_details: false,
            competitor: true,
            competitor_details: 'Enterprise tier only. Limited to code hosted on GitHub.',
            view_competitor_details: false,
        },
        {
            feature: 'Fine-tuned LLM',
            feature_details: '',
            view_feature_details: false,
            cody: false,
            cody_details: '',
            view_cody_details: false,
            competitor: true,
            competitor_details: 'Enterprise tier only.',
            view_competitor_details: false,
        },
    ],
    pricingSupport: [
        {
            feature: 'Free tier offered',
            feature_details: '',
            view_feature_details: false,
            cody: true,
            cody_details: '',
            view_cody_details: false,
            competitor: false,
            competitor_details: 'Free for students, teachers, and OSS maintainers',
            view_competitor_details: false,
        },
        {
            feature: 'Pro tier pricing for individuals',
            feature_details: '',
            view_feature_details: false,
            cody: '$9 / user / month',
            cody_details: '',
            view_cody_details: false,
            competitor: '$10 / user / month',
            competitor_details: '',
            view_competitor_details: false,
        },
        {
            feature: 'Enterprise tier pricing',
            feature_details: '',
            view_feature_details: false,
            cody: '$19 / user / month',
            cody_details: '',
            view_cody_details: false,
            competitor: '$39 / user / month',
            competitor_details: 'Requires GitHub Enterprise Cloud',
            view_competitor_details: false,
        },
    ],
}

export const codeiumVsCody: CompareDataType = {
    competitorName: 'Codeium',
    featureSupport: [
        {
            feature: 'Autocomplete',
            feature_details: '',
            view_feature_details: false,
            cody: true,
            cody_details: '',
            view_cody_details: false,
            competitor: true,
            competitor_details: '',
            view_competitor_details: false,
        },
        {
            feature: 'Chat',
            feature_details: '',
            view_feature_details: false,
            cody: true,
            cody_details: '',
            view_cody_details: false,
            competitor: true,
            competitor_details: '',
            view_competitor_details: false,
        },
        {
            feature: 'Commands',
            feature_details: '',
            view_feature_details: false,
            cody: true,
            cody_details: '',
            view_cody_details: false,
            competitor: false,
            competitor_details: '',
            view_competitor_details: false,
        },
        {
            feature: 'Custom commands',
            feature_details: '',
            view_feature_details: false,
            cody: true,
            cody_details: '',
            view_cody_details: false,
            competitor: false,
            competitor_details: '',
            view_competitor_details: false,
        },
    ],
    ideSupport: [
        {
            feature: 'Visual Studio Code',
            feature_details: '',
            view_feature_details: false,
            cody: true,
            cody_details: '',
            view_cody_details: false,
            competitor: true,
            competitor_details: '',
            view_competitor_details: false,
        },
        {
            feature: 'JetBrains',
            feature_details: '',
            view_feature_details: false,
            cody: true,
            cody_details: '',
            view_cody_details: false,
            competitor: true,
            competitor_details: '',
            view_competitor_details: false,
        },
        {
            feature: 'Visual Studio',
            feature_details: '',
            view_feature_details: false,
            cody: false,
            cody_details: '',
            view_cody_details: false,
            competitor: true,
            competitor_details: '',
            view_competitor_details: false,
        },
        {
            feature: 'Other',
            feature_details: '',
            view_feature_details: false,
            cody: true,
            cody_details: ['Neovim'],
            view_cody_details: false,
            competitor: true,
            competitor_details: ['Neovim ', 'Eclipse ', 'Xcode ', 'Sublime ', 'Emacs '],
            view_competitor_details: false,
        },
    ],
    llmSupport: [
        {
            feature: 'Chat model (default)',
            feature_details: '',
            view_feature_details: false,
            cody: 'Claude 2',
            cody_details: '',
            view_cody_details: false,
            competitor: 'Proprietary',
            competitor_details: '',
            view_competitor_details: false,
        },
        {
            feature: 'Autocomplete model (default)',
            feature_details: '',
            view_feature_details: false,
            cody: 'StarCoder',
            cody_details: '',
            view_cody_details: false,
            competitor: 'Not disclosed',
            competitor_details: '',
            view_competitor_details: false,
        },
        {
            feature: 'Choose your LLM',
            feature_details: '',
            view_feature_details: false,
            cody: true,
            cody_details: '',
            view_cody_details: false,
            competitor: false,
            competitor_details: '',
            view_competitor_details: false,
        },
        {
            feature: 'Bring your own LLM key',
            feature_details: '',
            view_feature_details: false,
            cody: true,
            cody_details: '',
            view_cody_details: false,
            competitor: false,
            competitor_details: '',
            view_competitor_details: false,
        },
        {
            feature: 'LLM hosting',
            feature_details: '',
            view_feature_details: false,
            cody: 'Cloud',
            cody_details: '',
            view_cody_details: false,
            competitor: 'Cloud or on-prem',
            competitor_details: '',
            view_competitor_details: false,
        },
    ],
    contextSupport: [
        {
            feature: 'Personalized responses using codebase context',
            feature_details: '',
            view_feature_details: false,
            cody: true,
            cody_details: 'Available on all tiers',
            view_cody_details: false,
            competitor: true,
            competitor_details: 'Available for all tiers',
            view_competitor_details: false,
        },
        {
            feature: 'Fine-tuned LLM',
            feature_details: '',
            view_feature_details: false,
            cody: false,
            cody_details: '',
            view_cody_details: false,
            competitor: true,
            competitor_details: 'Enterprise tier',
            view_competitor_details: false,
        },
    ],
    pricingSupport: [
        {
            feature: 'Free tier offered',
            feature_details: '',
            view_feature_details: false,
            cody: true,
            cody_details: '',
            view_cody_details: false,
            competitor: true,
            competitor_details: '',
            view_competitor_details: false,
        },
        {
            feature: 'Pro tier pricing for individuals',
            feature_details: '',
            view_feature_details: false,
            cody: '$9 / user / month',
            cody_details: '',
            view_cody_details: false,
            competitor: '$15 / user / month',
            competitor_details: '',
            view_competitor_details: false,
        },
    ],
}

export const amazonCodewhispererVsCody: CompareDataType = {
    competitorName: 'Amazon CodeWhisperer',
    featureSupport: [
        {
            feature: 'Autocomplete',
            feature_details: '',
            view_feature_details: false,
            cody: true,
            cody_details: '',
            view_cody_details: false,
            competitor: true,
            competitor_details: '',
            view_competitor_details: false,
        },
        {
            feature: 'Chat',
            feature_details: '',
            view_feature_details: false,
            cody: true,
            cody_details: '',
            view_cody_details: false,
            competitor: true,
            competitor_details: 'Preview',
            view_competitor_details: false,
        },
        {
            feature: 'Commands',
            feature_details: '',
            view_feature_details: false,
            cody: true,
            cody_details: '',
            view_cody_details: false,
            competitor: false,
            competitor_details: '',
            view_competitor_details: false,
        },
        {
            feature: 'Custom commands',
            feature_details: '',
            view_feature_details: false,
            cody: true,
            cody_details: '',
            view_cody_details: false,
            competitor: false,
            competitor_details: '',
            view_competitor_details: false,
        },
        {
            feature: 'Security vulnerability scanning',
            feature_details: '',
            view_feature_details: false,
            cody: false,
            cody_details: '',
            view_cody_details: false,
            competitor: true,
            competitor_details: '',
            view_competitor_details: false,
        },
    ],
    ideSupport: [
        {
            feature: 'Visual Studio Code',
            feature_details: '',
            view_feature_details: false,
            cody: true,
            cody_details: '',
            view_cody_details: false,
            competitor: true,
            competitor_details: '',
            view_competitor_details: false,
        },
        {
            feature: 'JetBrains',
            feature_details: '',
            view_feature_details: false,
            cody: true,
            cody_details: '',
            view_cody_details: false,
            competitor: true,
            competitor_details: '',
            view_competitor_details: false,
        },
        {
            feature: 'Visual Studio',
            feature_details: '',
            view_feature_details: false,
            cody: false,
            cody_details: '',
            view_cody_details: false,
            competitor: false,
            competitor_details: '',
            view_competitor_details: false,
        },
        {
            feature: 'Other',
            feature_details: '',
            view_feature_details: false,
            cody: true,
            cody_details: ['Neovim'],
            view_cody_details: false,
            competitor: true,
            competitor_details: ['AWS Cloud9', 'AWS Lambda'],
            view_competitor_details: false,
        },
    ],
    llmSupport: [
        {
            feature: 'Chat model (default)',
            feature_details: '',
            view_feature_details: false,
            cody: 'Claude 2',
            cody_details: '',
            view_cody_details: false,
            competitor: false,
            competitor_details: '',
            view_competitor_details: false,
        },
        {
            feature: 'Autocomplete model (default)',
            feature_details: '',
            view_feature_details: false,
            cody: 'StarCoder',
            cody_details: '',
            view_cody_details: false,
            competitor: 'Not disclosed',
            competitor_details: '',
            view_competitor_details: false,
        },
        {
            feature: 'Choose your LLM',
            feature_details: '',
            view_feature_details: false,
            cody: true,
            cody_details: '',
            view_cody_details: false,
            competitor: false,
            competitor_details: '',
            view_competitor_details: false,
        },
        {
            feature: 'Bring your own LLM key',
            feature_details: '',
            view_feature_details: false,
            cody: true,
            cody_details: '',
            view_cody_details: false,
            competitor: false,
            competitor_details: '',
            view_competitor_details: false,
        },
        {
            feature: 'LLM hosting',
            feature_details: '',
            view_feature_details: false,
            cody: 'Cloud',
            cody_details: '',
            view_cody_details: false,
            competitor: 'Cloud',
            competitor_details: '',
            view_competitor_details: false,
        },
    ],
    contextSupport: [
        {
            feature: 'Personalized responses using codebase context',
            feature_details: '',
            view_feature_details: false,
            cody: true,
            cody_details: 'Available on all tiers',
            view_cody_details: false,
            competitor: true,
            competitor_details: 'Preview for Enterprise tier',
            view_competitor_details: false,
        },
        {
            feature: 'Fine-tuned LLM',
            feature_details: '',
            view_feature_details: false,
            cody: false,
            cody_details: '',
            view_cody_details: false,
            competitor: true,
            competitor_details: 'Preview for Enterprise tier',
            view_competitor_details: false,
        },
    ],
    pricingSupport: [
        {
            feature: 'Free tier offered',
            feature_details: '',
            view_feature_details: false,
            cody: true,
            cody_details: '',
            view_cody_details: false,
            competitor: true,
            competitor_details: '',
            view_competitor_details: false,
        },
    ],
}

export const cursorVsCody: CompareDataType = {
    competitorName: 'Cursor',
    featureSupport: [
        {
            feature: 'Autocomplete',
            feature_details: '',
            view_feature_details: false,
            cody: true,
            cody_details: '',
            view_cody_details: false,
            competitor: true,
            competitor_details: '',
            view_competitor_details: false,
        },
        {
            feature: 'Chat',
            feature_details: '',
            view_feature_details: false,
            cody: true,
            cody_details: '',
            view_cody_details: false,
            competitor: true,
            competitor_details: '',
            view_competitor_details: false,
        },
        {
            feature: 'Commands',
            feature_details: '',
            view_feature_details: false,
            cody: true,
            cody_details: '',
            view_cody_details: false,
            competitor: false,
            competitor_details: '',
            view_competitor_details: false,
        },
        {
            feature: 'Custom commands',
            feature_details: '',
            view_feature_details: false,
            cody: true,
            cody_details: '',
            view_cody_details: false,
            competitor: false,
            competitor_details: '',
            view_competitor_details: false,
        },
    ],
    ideSupport: [
        {
            feature: 'Visual Studio Code',
            feature_details: '',
            view_feature_details: false,
            cody: true,
            cody_details: '',
            view_cody_details: false,
            competitor: true,
            competitor_details: 'Cursor is a standalone fork of VS Code',
            view_competitor_details: false,
        },
        {
            feature: 'JetBrains',
            feature_details: '',
            view_feature_details: false,
            cody: true,
            cody_details: '',
            view_cody_details: false,
            competitor: false,
            competitor_details: '',
            view_competitor_details: false,
        },
        {
            feature: 'Visual Studio',
            feature_details: '',
            view_feature_details: false,
            cody: false,
            cody_details: '',
            view_cody_details: false,
            competitor: false,
            competitor_details: '',
            view_competitor_details: false,
        },
        {
            feature: 'Other',
            feature_details: '',
            view_feature_details: false,
            cody: true,
            cody_details: '',
            view_cody_details: false,
            competitor: false,
            competitor_details: '',
            view_competitor_details: false,
        },
    ],
    llmSupport: [
        {
            feature: 'Chat model (default)',
            feature_details: '',
            view_feature_details: false,
            cody: 'Claude 2',
            cody_details: '',
            view_cody_details: false,
            competitor: 'GPT-3.5',
            competitor_details: '',
            view_competitor_details: false,
        },
        {
            feature: 'Autocomplete model (default)',
            feature_details: '',
            view_feature_details: false,
            cody: 'StarCoder',
            cody_details: '',
            view_cody_details: false,
            competitor: false,
            competitor_details: '',
            view_competitor_details: false,
        },
        {
            feature: 'Choose your LLM',
            feature_details: '',
            view_feature_details: false,
            cody: true,
            cody_details: '',
            view_cody_details: false,
            competitor: true,
            competitor_details: '',
            view_competitor_details: false,
        },
        {
            feature: 'Bring your own LLM key',
            feature_details: '',
            view_feature_details: false,
            cody: true,
            cody_details: '',
            view_cody_details: false,
            competitor: true,
            competitor_details: '',
            view_competitor_details: false,
        },
        {
            feature: 'LLM hosting',
            feature_details: '',
            view_feature_details: false,
            cody: 'Cloud',
            cody_details: '',
            view_cody_details: false,
            competitor: 'Cloud',
            competitor_details: '',
            view_competitor_details: false,
        },
        {
            feature: 'Pro tier pricing for individuals',
            feature_details: '',
            view_feature_details: false,
            cody: '$9 / user / month',
            cody_details: '',
            view_cody_details: false,
            competitor: '$20 / user / month',
            competitor_details: '',
            view_competitor_details: false,
        },
    ],
    contextSupport: [
        {
            feature: 'Personalized responses using codebase context',
            feature_details: '',
            view_feature_details: false,
            cody: true,
            cody_details: 'Available on all tiers',
            view_cody_details: false,
            competitor: true,
            competitor_details: 'Available on all tiers',
            view_competitor_details: false,
        },
        {
            feature: 'Fine-tuned LLM',
            feature_details: '',
            view_feature_details: false,
            cody: false,
            cody_details: '',
            view_cody_details: false,
            competitor: false,
            competitor_details: 'Waitlist for Enterprise tier',
            view_competitor_details: false,
        },
    ],
    pricingSupport: [
        {
            feature: 'Free tier offered',
            feature_details: '',
            view_feature_details: false,
            cody: true,
            cody_details: '',
            view_cody_details: false,
            competitor: false,
            competitor_details: 'Free for students, teachers, and OSS mainters',
            view_competitor_details: false,
        },
    ],
}

export const tabnineVsCody: CompareDataType = {
    competitorName: 'Tabnine',
    featureSupport: [
        {
            feature: 'Autocomplete',
            feature_details: '',
            view_feature_details: false,
            cody: true,
            cody_details: '',
            view_cody_details: false,
            competitor: true,
            competitor_details: 'Limited to 2-3 word completions on free tier',
            view_competitor_details: false,
        },
        {
            feature: 'Chat',
            feature_details: '',
            view_feature_details: false,
            cody: true,
            cody_details: '',
            view_cody_details: false,
            competitor: true,
            competitor_details: 'Available for Pro and Enterprise users',
            view_competitor_details: false,
        },
        {
            feature: 'Commands',
            feature_details: '',
            view_feature_details: false,
            cody: true,
            cody_details: '',
            view_cody_details: false,
            competitor: true,
            competitor_details: '',
            view_competitor_details: false,
        },
        {
            feature: 'Custom commands',
            feature_details: '',
            view_feature_details: false,
            cody: true,
            cody_details: '',
            view_cody_details: false,
            competitor: true,
            competitor_details: '',
            view_competitor_details: false,
        },
    ],
    ideSupport: [
        {
            feature: 'Visual Studio Code',
            feature_details: '',
            view_feature_details: false,
            cody: true,
            cody_details: '',
            view_cody_details: false,
            competitor: true,
            competitor_details: '',
            view_competitor_details: false,
        },
        {
            feature: 'JetBrains',
            feature_details: '',
            view_feature_details: false,
            cody: true,
            cody_details: '',
            view_cody_details: false,
            competitor: true,
            competitor_details: '',
            view_competitor_details: false,
        },
        {
            feature: 'Visual Studio',
            feature_details: '',
            view_feature_details: false,
            cody: false,
            cody_details: '',
            view_cody_details: false,
            competitor: true,
            competitor_details: '',
            view_competitor_details: false,
        },
        {
            feature: 'Other',
            feature_details: '',
            view_feature_details: false,
            cody: true,
            cody_details: ['Neovim'],
            view_cody_details: false,
            competitor: true,
            competitor_details: ['Eclipse'],
            view_competitor_details: false,
        },
    ],
    llmSupport: [
        {
            feature: 'Chat model (default)',
            feature_details: '',
            view_feature_details: false,
            cody: 'Claude 2',
            cody_details: '',
            view_cody_details: false,
            competitor: 'Proprietary',
            competitor_details: '',
            view_competitor_details: false,
        },
        {
            feature: 'Autocomplete model (default)',
            feature_details: '',
            view_feature_details: false,
            cody: 'StarCoder',
            cody_details: '',
            view_cody_details: false,
            competitor: 'Proprietary',
            competitor_details: '',
            view_competitor_details: false,
        },
        {
            feature: 'Choose your LLM',
            feature_details: '',
            view_feature_details: false,
            cody: true,
            cody_details: '',
            view_cody_details: false,
            competitor: false,
            competitor_details: '',
            view_competitor_details: false,
        },
        {
            feature: 'Bring your own LLM key',
            feature_details: '',
            view_feature_details: false,
            cody: true,
            cody_details: '',
            view_cody_details: false,
            competitor: false,
            competitor_details: '',
            view_competitor_details: false,
        },
        {
            feature: 'LLM hosting',
            feature_details: '',
            view_feature_details: false,
            cody: 'Cloud',
            cody_details: '',
            view_cody_details: false,
            competitor: 'Cloud or on-prem',
            competitor_details: '',
            view_competitor_details: false,
        },
        {
            feature: 'Pro tier pricing for individuals',
            feature_details: '',
            view_feature_details: false,
            cody: '$9 / user / month',
            cody_details: '',
            view_cody_details: false,
            competitor: '$12 / user / month',
            competitor_details: '',
            view_competitor_details: false,
        },
    ],
    contextSupport: [
        {
            feature: 'Personalized responses using codebase context',
            feature_details: '',
            view_feature_details: false,
            cody: true,
            cody_details: 'Available on all tiers',
            view_cody_details: false,
            competitor: false,
            competitor_details: 'Coming soon for Enterprise tier',
            view_competitor_details: false,
        },
        {
            feature: 'Fine-tuned LLM',
            feature_details: '',
            view_feature_details: false,
            cody: false,
            cody_details: '',
            view_cody_details: false,
            competitor: true,
            competitor_details: 'Enterprise tier',
            view_competitor_details: false,
        },
    ],
    pricingSupport: [
        {
            feature: 'Free tier offered',
            feature_details: '',
            view_feature_details: false,
            cody: true,
            cody_details: '',
            view_cody_details: false,
            competitor: true,
            competitor_details: '',
            view_competitor_details: false,
        },
    ],   
}

export const continueVsCody: CompareDataType = {
    competitorName: 'Continue',
    featureSupport: [
        {
            feature: 'Autocomplete',
            feature_details: '',
            view_feature_details: false,
            cody: true,
            cody_details: '',
            view_cody_details: false,
            competitor: true,
            competitor_details: '',
            view_competitor_details: false,
        },
        {
            feature: 'Chat',
            feature_details: '',
            view_feature_details: false,
            cody: true,
            cody_details: '',
            view_cody_details: false,
            competitor: true,
            competitor_details: '',
            view_competitor_details: false,
        },
        {
            feature: 'Commands',
            feature_details: '',
            view_feature_details: false,
            cody: true,
            cody_details: '',
            view_cody_details: false,
            competitor: false,
            competitor_details: '',
            view_competitor_details: false,
        },
        {
            feature: 'Custom commands',
            feature_details: '',
            view_feature_details: false,
            cody: true,
            cody_details: '',
            view_cody_details: false,
            competitor: false,
            competitor_details: '',
            view_competitor_details: false,
        },
    ],
    ideSupport: [
        {
            feature: 'Visual Studio Code',
            feature_details: '',
            view_feature_details: false,
            cody: true,
            cody_details: '',
            view_cody_details: false,
            competitor: true,
            competitor_details: '',
            view_competitor_details: false,
        },
        {
            feature: 'JetBrains',
            feature_details: '',
            view_feature_details: false,
            cody: true,
            cody_details: '',
            view_cody_details: false,
            competitor: true,
            competitor_details: '',
            view_competitor_details: false,
        },
        {
            feature: 'Visual Studio',
            feature_details: '',
            view_feature_details: false,
            cody: false,
            cody_details: '',
            view_cody_details: false,
            competitor: false,
            competitor_details: '',
            view_competitor_details: false,
        },
        {
            feature: 'Other',
            feature_details: '',
            view_feature_details: false,
            cody: true,
            cody_details: ['Neovim'],
            view_cody_details: false,
            competitor: false,
            competitor_details: '',
            view_competitor_details: false,
        },
    ],
    llmSupport: [
        {
            feature: 'Chat model (default)',
            feature_details: '',
            view_feature_details: false,
            cody: 'Claude 3 Sonnet',
            cody_details: '',
            view_cody_details: false,
            competitor: 'Code Llama',
            competitor_details: '7B parameters via Ollama',
            view_competitor_details: false,
        },
        {
            feature: 'Autocomplete model (default)',
            feature_details: '',
            view_feature_details: false,
            cody: 'StarCoder',
            cody_details: '',
            view_cody_details: false,
            competitor: 'StarCoder',
            competitor_details: '2B parameters via Ollama',
            view_competitor_details: false,
        },
        {
            feature: 'Choose your LLM',
            feature_details: '',
            view_feature_details: false,
            cody: true,
            cody_details: '',
            view_cody_details: false,
            competitor: true,
            competitor_details: '',
            view_competitor_details: false,
        },
        {
            feature: 'Bring your own LLM key',
            feature_details: '',
            view_feature_details: false,
            cody: true,
            cody_details: '',
            view_cody_details: false,
            competitor: true,
            competitor_details: '',
            view_competitor_details: false,
        },
        {
            feature: 'LLM hosting',
            feature_details: '',
            view_feature_details: false,
            cody: 'Cloud or local',
            cody_details: 'With experimental Ollama support',
            view_cody_details: false,
            competitor: 'Cloud or local',
            competitor_details: '',
            view_competitor_details: false,
        },
        {
            feature: 'Pro tier pricing for individuals',
            feature_details: '',
            view_feature_details: false,
            cody: '$9 / user / month',
            cody_details: '',
            view_cody_details: false,
            competitor: '$0 / user / month',
            competitor_details: '',
            view_competitor_details: false,
        },
    ],
    contextSupport: [
        {
            feature: 'Personalized responses using codebase context',
            feature_details: '',
            view_feature_details: false,
            cody: true,
            cody_details: 'Available on all tiers',
            view_cody_details: false,
            competitor: true,
            competitor_details: '',
            view_competitor_details: false,
        },
        {
            feature: 'Fine-tuned LLM',
            feature_details: '',
            view_feature_details: false,
            cody: false,
            cody_details: '',
            view_cody_details: false,
            competitor: true,
            competitor_details: '',
            view_competitor_details: false,
        },
    ],
    pricingSupport: [
        {
            feature: 'Free tier offered',
            feature_details: '',
            view_feature_details: false,
            cody: true,
            cody_details: '',
            view_cody_details: false,
            competitor: true,
            competitor_details: '',
            view_competitor_details: false,
        },
    ],   
}
