import { FunctionComponent, ReactNode, useEffect, useState } from 'react'

import { DotLottiePlayer } from '@dotlottie/react-player'
import classNames from 'classnames'
import ChevronRightIcon from 'mdi-react/ChevronRightIcon'
import Link from 'next/link'
import { MdOutlineSecurity, MdVpnKey, MdLock, MdDoNotDisturb } from 'react-icons/md'

import { Layout, Hero, ContentSection, Heading } from '../components'
import { breakpoints } from '../data/breakpoints'
import { buttonLocation, buttonStyle } from '../data/tracking'
import { useWindowWidth } from '../hooks/windowWidth'

const enterpriseDevPlatforms = [
    { src: '/enterprise/vscode.svg', alt: 'Visual Studio Code' },
    { src: '/enterprise/github.svg', alt: 'GitHub' },
    { src: '/enterprise/bitbucket.svg', alt: 'Bitbucket' },
    { src: '/enterprise/intellij.svg', alt: 'IntelliJ' },
    { src: '/enterprise/neovim.svg', alt: 'Neovim' },
    { src: '/enterprise/golang.svg', alt: 'Golang' },
    { src: '/enterprise/gerrit.svg', alt: 'Gerrit' },
    { src: '/enterprise/gitlab.svg', alt: 'GitLab' },
    { src: '/enterprise/perforce.svg', alt: 'Perforce' },
]

const enterpriseDevTools = [
    { src: '/enterprise/ai.svg', alt: 'ai' },
    { src: '/enterprise/open-ai.svg', alt: 'open ai' },
    { src: '/enterprise/amazon-bedrock.svg', alt: 'amazon bedrock' },
    { src: '/enterprise/microsoft-azure.svg', alt: 'microsoft azure' },
    { src: '/enterprise/ai-cut.svg', alt: 'ai cut' },
]

const enterpriseDevToolsMobile = [
    { src: '/enterprise/microsoft-azure.svg', alt: 'microsoft azure' },
    { src: '/enterprise/ai.svg', alt: 'ai' },
    { src: '/enterprise/amazon-bedrock.svg', alt: 'amazon bedrock' },
    { src: '/enterprise/open-ai.svg', alt: 'open ai' },
]

const enterpriseCardObjects = [
    {
        heading: 'Deployment options for every team',
        paragraph:
            'Choose Sourcegraph Cloud, our single-tenant cloud solution, or self-host Sourcegraph in your preferred environment.',
    },
    {
        heading: 'Admin usage analytics',
        paragraph: 'Admins can see anonymized, event-level usage analytics for each feature their teams are using.',
    },
    {
        heading: 'Granular user permissions',
        paragraph:
            'Sync repository permissions with GitHub, GitLab, Bitbucket Cloud, Gerrit, or Perforce. Alternatively, set your own custom, repository-level permissions.',
    },
    {
        heading: 'Authentication with SAML and code host OAuth',
        paragraph:
            'Admins can choose from multiple user authentication options, including SAML or OAuth via GitHub or GitLab.',
    },
    {
        heading: 'SCIM user provisioning',
        paragraph: 'Provision and de-provision users with SCIM for Okta and Azure Active Directory.',
    },
]

const securityFeatures = [
    {
        imgSrc: ['/security/soc2.svg'],
        altText: 'SOC 2 Type 2 compliance',
        heading: 'SOC 2 Type 2 compliance',
        paragraph: (
            <>
                Data privacy is a priority, and Sourcegraph has received a SOC 2 Type 2 report. See our
                <Link
                    href="https://security.sourcegraph.com/"
                    title="security portal"
                    className="mx-[3px] text-black underline underline-offset-[3.55px] "
                >
                    security portal
                </Link>
                for more information.
            </>
        ),
    },
    {
        imgSrc: ['/security/gdpr.svg', '/security/ccpa.svg'],
        altText: 'GDPR and CCPA',
        heading: 'GDPR + CCPA',
        paragraph:
            'Sourcegraph is compliant with the CCPA and operates in accordance with GDPR data protection regulations.',
    },
    {
        imgSrc: ['/enterprise/notes.svg'],
        altText: 'Notes',
        heading: 'Audit logs',
        paragraph: 'Sourcegraph logs security and access events for security teams’ peace of mind.',
    },
]

const securityCardFeatures = [
    {
        icon: <MdDoNotDisturb size={24} />,
        heading: 'Zero retention',
        paragraph:
            'Our provided LLMs do not retain data from your requests for longer than the time it takes to generate an output.',
    },
    {
        icon: <MdVpnKey size={24} />,
        heading: 'You retain ownership',
        paragraph: 'You retain ownership of all inputs and output generated by Cody.',
    },
    {
        icon: <MdOutlineSecurity size={24} />,
        heading: 'Uncapped indemnity',
        paragraph: 'We provide full IP indemnity to enterprise customers.',
    },
]

const Enterprise: FunctionComponent = () => {
    const windowWidth = useWindowWidth()
    const isMobile = windowWidth < breakpoints.md
    const lgAndUp = windowWidth > breakpoints.lg

    const [videoPlayed, setVideoPlayed] = useState(false)

    useEffect(() => {
        const videoDuration = 3090
        const transitionTime = 200

        const timeout = setTimeout(() => {
            setVideoPlayed(true)
        }, videoDuration - transitionTime)

        return () => clearTimeout(timeout)
    }, [])

    return (
        <Layout
            meta={{
                title: 'Sourcegraph - Enterprise',
                description:
                    "Give your teams the ability to search, write, and understand massive codebases through Sourcegraph's universal and secure Code Intelligence Platform.",
            }}
            className="bg-gray-50"
            hero={
                <div className="">
                    {!isMobile && (
                        <div className="absolute inset-0 top-[48px] mx-auto max-w-[1280px] z-0 h-full transition-opacity duration-1000 ease-in-out">
                            <DotLottiePlayer
                                className={`absolute inset-0 top-[30px] z-0 h-full w-full object-cover opacity-${
                                    videoPlayed ? '0' : '100'
                                }`}
                                src="https://lottie.host/07b21a4d-e532-47b7-ab01-7bd8faf4ba33/ORhWKPLwKI.lottie"
                                background="transparent"
                                speed={1}
                                direction={1}
                                autoplay={true}
                                loop={false}
                                renderer="svg"
                            />
                            <div
                                className={`absolute inset-0 top-[30px] z-0 h-full w-full bg-contain bg-center bg-no-repeat opacity-${
                                    videoPlayed ? '100' : '0'
                                }`}
                                // eslint-disable-next-line react/forbid-dom-props
                                style={{ backgroundImage: "url('enterprise/Enterprise-hero-still.png')" }}
                            />
                        </div>
                    )}
                    <Hero
                        variant="transparent"
                        className="relative z-10 mx-auto flex items-center justify-center !pt-[122px] pb-8  text-center md:!mt-[-36px] md:w-[750px]  md:pb-[96px]"
                        title="Modern enterprises are powered by productive developers"
                        subtitle="Give your teams the ability to search, write, and understand massive codebases through Sourcegraph's universal and secure Code Intelligence Platform."
                        centerContent={true}
                        cta={
                            <div className="mx-auto flex w-[356px] flex-col items-center justify-center gap-6 sm:flex sm:w-auto  sm:flex-row  md:gap-4">
                                <Link
                                    className="btn btn-primary w-full bg-violet-500 sm:w-auto"
                                    href="/contact/request-info"
                                    title="Contact us for a demo"
                                    data-button-style={buttonStyle.primary}
                                    data-button-location={buttonLocation}
                                    data-button-type="cta"
                                >
                                    Contact us for a demo
                                </Link>
                                <Link
                                    className="btn  w-full items-center text-violet-500 outline sm:w-auto"
                                    href="/pricing"
                                    title="See Pricing"
                                    data-button-style={buttonStyle.outline}
                                    data-button-location={buttonLocation.hero}
                                    data-button-type="cta"
                                >
                                    See pricing
                                </Link>
                            </div>
                        }
                        displayUnderNav={true}
                    />
                </div>
            }
        >
            <ContentSection
                className="relative mx-auto mt-0 flex flex-col items-center gap-12 py-16 text-center md:mt-[-135px] md:pt-[282px] md:pb-[96px]"
                parentClassName="!py-0 md:px-[80px]"
            >
                <div className="z-10 flex flex-col items-center gap-6  text-center md:w-[615px]">
                    <h2>Used by 6 of the 10 largest software companies in the world</h2>
                    <Link
                        href="https://sourcegraph.com/case-studies"
                        title="Cody"
                        className="btn p-0 text-center font-semibold hover:underline  !-tracking-[0.25px]  text-violet-500 md:text-violet-500"
                    >
                        Read customer stories
                        <ChevronRightIcon className="!mb-0 ml-[10px] inline" />
                    </Link>
                </div>
                <div className="flex flex-wrap items-center justify-center gap-[42px] ">
                    <img className="" src="/enterprise/cern-logo.svg" alt="Cody Product logo" />
                    <img className="" src="/enterprise/mercado-libre-logo.svg" alt="Cody Product logo" />
                    <img className="" src="/enterprise/SoFi-logo.svg" alt="Cody Product logo" />
                    <img className="" src="/enterprise/qualtrics-logo.svg" alt="Cody Product logo" />
                    <img className="" src="/enterprise/leidos-logo.svg" alt="Cody Product logo" />
                </div>
            </ContentSection>
            <ContentSection
                className="relative flex z-10 max-w-[1232px] flex-col gap-6 md:flex-row"
                parentClassName="!md:px-[80px] !py-0"
            >
                <div className="flex h-[533px] flex-col justify-between px-0 py-16 md:px-10">
                    <div className="flex flex-col gap-4">
                        <Heading size="h2" className="!tracking-[-1px] text-black">
                            Improve velocity with faster code discovery and understanding
                        </Heading>
                        <p className="mb-0 text-lg leading-[27px] tracking-[-0.25px]">
                            Developers can find, navigate, and share code across entire codebases in seconds, increasing
                            development velocity and reducing time spent searching for answers.
                        </p>
                    </div>
                    <div className="flex flex-row justify-center gap-7">
                        <img className="" src="/enterprise/cody-search.svg" alt="Cody and Code Search Product logo" />
                    </div>
                </div>
                <div className="h-auto rounded-2xl border-1 border-gray-200 bg-white px-6 py-16  md:max-w-[574px] md:px-20">
                    <p className="mb-0 leading-6 tracking-[-0.25px] text-gray-700">Satish Surapaneni</p>
                    <p className="mb-0 text-sm leading-[19.88px]">Senior Engineering Manager, F5</p>
                    <p className="mb-0 pt-3 text-[35px] font-normal leading-[43.75px] -tracking-[2px]">
                        "We are developing software faster than ever, with aggressive schedules, and across boundaries.
                        Things that used to be worked out in a closed room now need to be done while teams are spread
                        out across the globe.”
                    </p>
                </div>
            </ContentSection>
            <ContentSection
                className="flex h-auto max-w-[1232px] flex-col-reverse justify-between gap-[19px] overflow-hidden rounded-2xl border-1 border-gray-200 bg-white md:h-[301px] md:flex-row"
                parentClassName="!py-16"
            >
                <div className="flex  flex-col px-6 py-10 md:py-16 md:pl-10">
                    <Heading size="h2" className="pb-4 pt-6 !leading-10 !tracking-[-1px] text-gray-700">
                        Developers write code faster using Cody and the power of AI in their IDE
                    </Heading>
                </div>
                <div className="md:sg-developers sg-developers-mobile  relative z-10 h-full w-full">
                    {isMobile ? (
                        <img
                            src="enterprise/multiline-completion.svg"
                            alt=""
                            className="relative h-[421px] w-[784px] pt-10"
                        />
                    ) : (
                        <img
                            className="sg-developers relative h-full w-full"
                            src="/home/multiline-completion.svg"
                            alt="Multiline Completion"
                        />
                    )}
                </div>
            </ContentSection>
            <ContentSection
                className="grid max-w-[1232px] grid-cols-1 gap-8 rounded-2xl border-1  border-gray-200 bg-white py-16 px-6 md:grid-cols-2 md:flex-row md:gap-6 md:pl-16 md:pr-6"
                parentClassName="md:px-[80px] !py-0"
            >
                <div className="flex items-center rounded-2xl border-1 border-gray-200 bg-gray-50 px-6 py-16 md:items-end lg:px-20">
                    <div className="flex flex-col">
                        <p className="mb-0 leading-6 tracking-[-0.25px] text-gray-700">Balázs Tóthfalussy</p>
                        <p className="mb-0 text-sm leading-[19.88px]">Engineering Manager, Prezi</p>
                        <p className="mb-0 pt-3 text-[35px] font-normal leading-[43.75px] -tracking-[2px]">
                            "As we’ve grown, so has the need to better track and communicate our progress and goals
                            across the engineering team and broader company...
                        </p>
                    </div>
                </div>
                <div className=" ">
                    <div className="lg:px-10">
                        <Heading size="h2" className="mb-4 !leading-10 !tracking-[-1px] text-black">
                            Complete large-scale migrations and refactors in hours rather than days
                        </Heading>
                        <p className="mb-4 text-lg md:mb-0 ">
                            Perform organization-wide migrations and upgrades across every repository and code host with
                            Batch Changes, and track migration progress with Code Insights dashboards.
                        </p>
                    </div>

                    {!isMobile ? (
                        <div className="lg:w-[558px]">
                            <img
                                src="enterprise/graph.svg"
                                alt="graph"
                                className="relative -right-10 xl:-right-[92px]"
                            />
                        </div>
                    ) : (
                        <img src="enterprise/mobile-graph.svg" alt="graph" className=" h-[344px] w-[408px] " />
                    )}
                </div>
            </ContentSection>
            <ContentSection
                className="flex max-w-[1232px] flex-col gap-6 md:flex-row"
                parentClassName="!md:px-[80px] !md:pb-[96px]"
            >
                <div className="md:pt-6 md:pl-16 md:pr-10">
                    <Heading size="h2" className="mb-4 pt-4 !leading-10 !tracking-[-1px] text-black md:pt-0">
                        Track and resolve vulnerabilities quickly and with confidence
                    </Heading>
                    <p className="mb-[37px] text-lg leading-[27px] tracking-[-0.25px]">
                        Find all instances of vulnerabilities with Code Search, then use Batch Changes to replace
                        vulnerable code all at once. Plus, Code Insights lets you create dashboards to track instances
                        of vulnerabilities or bad code patterns over time.
                    </p>
                    <img src="enterprise/batch-change.svg" alt="code search" />
                </div>
                <div className="rounded-2xl border-1 border-gray-200 bg-white px-6 py-16 md:max-w-[576px] md:px-16">
                    <p className="mb-5 text-[35px] font-normal leading-[43.75px] -tracking-[2px] text-gray-700">
                        “It's nice when you can just run a report and say, 'Here it is,' or 'Here it isn't.' It's much
                        better than having to say, 'Well, boss, I think we got it all.'”
                    </p>
                    <p className="mb-0 leading-6 tracking-[-0.25px] text-gray-700">Jon Kohler</p>
                    <p className="mb-0 text-sm leading-[19.88px]">
                        Nutanix, after responding to the Log4J vulnerability
                    </p>
                </div>
            </ContentSection>
            <ContentSection
                className="flex max-w-[1232px] flex-col justify-between rounded-2xl border-1 border-gray-200  bg-violet-700 py-16 px-[56px] md:flex-row"
                parentClassName="md:px-[80px] !py-0 md:!pb-[96px] !pb-[64px]"
            >
                <Heading size="h2" className="mb-8 !leading-10 !tracking-[-1px] text-white md:mb-0">
                    Request a demo or start an enterprise trial
                </Heading>
                <div className="flex max-w-[356px] flex-col flex-wrap items-center gap-6 sm:flex-row md:gap-4">
                    <Link
                        className="btn btn-inverted-primary w-full border-gray-200 bg-white text-center text-violet-500 md:w-auto"
                        href="/contact/request-info"
                        title="Contact us"
                        data-button-style={buttonStyle.primary}
                        data-button-location={buttonLocation}
                        data-button-type="cta"
                    >
                        Contact us
                    </Link>
                    <Link
                        className="btn w-full items-center text-center text-white outline md:w-auto"
                        href="/pricing"
                        title="See Pricing"
                        data-button-style={buttonStyle.outline}
                        data-button-location={buttonLocation.hero}
                        data-button-type="cta"
                    >
                        See pricing
                    </Link>
                </div>
            </ContentSection>
            <ContentSection
                className="flex max-w-[1232px] flex-col justify-between overflow-hidden  rounded-2xl  border-1 border-gray-200 bg-white px-6 md:flex-row md:px-16"
                parentClassName="md:px-[80px] !py-0"
            >
                <div className="flex flex-col justify-center pt-16 !pb-12 md:w-[492px] md:py-16">
                    <img
                        alt="language models brand"
                        className="mb-6 w-12"
                        src="/enterprise/language-models-brand-icon.svg"
                    />
                    <Heading size="h1" className="mb-4">
                        Universal
                    </Heading>
                    <p className="mb-0 text-[24px] leading-[30px] -tracking-[0.25px]">
                        You don't have to compromise. Sourcegraph works with all major code hosts and IDEs to understand
                        all your code.
                    </p>
                </div>
                <div className="flex w-auto justify-center gap-[37px] md:gap-[31.97px]">
                    <div className="relative bottom-[17px] flex flex-col gap-[25.21px]">
                        {enterpriseDevPlatforms.slice(0, 3).map(({ src, alt }) => (
                            <EnterpriseIcon className="flex justify-center" key={alt} src={src} alt={alt} />
                        ))}
                    </div>
                    <div className="relative flex flex-col gap-[25px] md:top-[21px]">
                        {enterpriseDevPlatforms.slice(3, 6).map(({ src, alt }) => (
                            <EnterpriseIcon className="flex justify-center" key={alt} src={src} alt={alt} />
                        ))}
                    </div>
                    <div className="relative bottom-[17px] flex flex-col gap-[25px]">
                        {enterpriseDevPlatforms.slice(6).map(({ src, alt }) => (
                            <EnterpriseIcon className="flex justify-center" key={alt} src={src} alt={alt} />
                        ))}
                    </div>
                </div>
            </ContentSection>
            <ContentSection
                className="grid max-w-[1232px] grid-cols-1 gap-6 py-8 md:grid-cols-2 md:py-0"
                parentClassName="md:px-[80px]"
            >
                <div className="rounded-2xl border-1 border-gray-200 bg-violet-700 !py-16 px-6 text-white md:px-20">
                    <p className="mb-0 leading-6 tracking-[-0.25px] text-white opacity-80">Satish Surapaneni</p>
                    <p className="mb-0 text-sm leading-[19.88px] text-white">Senior Engineering Manager, F5</p>
                    <p className="mb-0 pt-6 text-[35px] font-normal leading-[43.75px] -tracking-[2px] md:max-w-[468px]">
                        “Before Sourcegraph, each of our teams was siloed. Developers could understand their own
                        codebase, but it was difficult for them to see and understand other team members’ code.“
                    </p>
                </div>
                <div className="relative flex flex-col overflow-hidden rounded-2xl border-1 border-gray-200 pt-[71px] sm:min-h-[558px]  md:min-h-[700px] md:py-[71px] md:pb-10">
                    <div className="flex flex-col gap-6 px-10 md:gap-4">
                        <Heading size="h6">cody</Heading>
                        <Heading size="h2" className="!leading-10 !tracking-[-1px]">
                            Choose from your favorite Large Language Models
                        </Heading>
                        <p className="mb-0 text-[18px] font-normal leading-[27px] -tracking-[0.25px]">
                            Cody, Sourcegraph’s AI coding assistant, lets you choose from multiple LLM options including
                            Anthropic Claude 2 and OpenAI GPT-4. You can even bring your own LLM key with Amazon Bedrock
                            and Azure OpenAI.
                        </p>
                    </div>
                    {!isMobile ? (
                        <div className="absolute bottom-6 -right-[100px] flex  gap-[21px] md:bottom-[71px] md:w-[731px]">
                            {enterpriseDevTools.map(({ src, alt }) => (
                                <EnterpriseIcon
                                    className="flex items-center justify-center"
                                    key={alt}
                                    src={src}
                                    alt={alt}
                                />
                            ))}
                        </div>
                    ) : (
                        <div className="relative  left-10 flex gap-[21px]  py-6 md:bottom-[71px] md:w-[731px]">
                            {enterpriseDevToolsMobile.map(({ src, alt }) => (
                                <EnterpriseIcon
                                    className="flex items-center justify-center"
                                    key={alt}
                                    src={src}
                                    alt={alt}
                                />
                            ))}
                        </div>
                    )}
                </div>
            </ContentSection>
            <ContentSection
                className="flex max-w-[1232px] flex-col justify-between overflow-hidden rounded-2xl border-1 border-gray-200 bg-white py-10  px-6 md:flex-row md:pr-10 md:pl-16"
                parentClassName="md:px-[80px] md:!py-16 py-8"
            >
                <div className="flex max-w-[532px] flex-col justify-center">
                    <img src="/enterprise/code-graph-brand-icon.svg" alt="" className="mb-6 w-[48px]" />
                    <Heading size="h2" className="mb-4 !text-[52px] !leading-[62px] !tracking-[-1px]">
                        Scalable
                    </Heading>
                    <Heading size="h3" className="mb-6 font-normal !leading-[30px] !-tracking-[0.25px] md:mb-0">
                        Leverage AI at any scale. Sourcegraph supports the world's largest codebases.
                    </Heading>
                </div>
                <div className="sg-scalable relative z-10 max-w-[477px]">
                    <div className=" relative flex  flex-col gap-16 rounded-2xl border-1 border-gray-200 bg-white py-10 pl-10 pr-[89px]">
                        <Heading size="h3" className="!leading-[30px] !-tracking-[0.25px]">
                            Customers run single-tenant Sourcegraph instances for codebases of epic size:
                        </Heading>
                        <div>
                            <p className="mb-0 font-sans text-[40px] font-semibold leading-[93.75px] -tracking-[0.25px] sm:text-[75px]">
                                8+
                            </p>
                            <Heading size="h3" className="!leading-[30px] !tracking-[-0.25px]">
                                Terabytes of code at finance industry customer
                            </Heading>
                        </div>
                        <div>
                            <p className="mb-0 font-sans text-[40px] font-semibold leading-[93.75px] -tracking-[0.25px] sm:text-[75px]">
                                100,000+
                            </p>
                            <Heading size="h3" className="!leading-[30px] !tracking-[-0.25px]">
                                Repositories at finance industry customer
                            </Heading>
                        </div>
                    </div>
                </div>
            </ContentSection>
            <ContentSection
                parentClassName="!py-0 md:px-[80px]"
                className="flex max-w-[1232px] flex-col gap-16 rounded-2xl border-1 bg-violet-700 py-16 px-6 text-white md:flex-row md:gap-[160px] md:px-20"
            >
                <div className="flex max-w-[511px] flex-col gap-[70px]">
                    <img src="enterprise/nine.svg" className="w-[188px]" alt="" />
                    <p className="mb-0 text-[35px] font-normal leading-[43.75px] -tracking-[0.25px]">
                        Nine’s Platform Engineering team saved hundreds of hours and thousands of dollars by using Code
                        Search and Batch Changes for their CI/CD refactor.
                    </p>
                </div>
                <div className="relative flex max-w-[479px] flex-col gap-16">
                    <div>
                        <p className="mb-0  font-sans text-[75px] font-semibold leading-[93.75px]">$276K</p>
                        <Heading size="h3" className="!leading-[30px] !tracking-[-0.25px] text-gray-200">
                            Engineering time saved
                        </Heading>
                    </div>
                    <div>
                        <p className="mb-0 font-sans text-[75px] font-semibold leading-[93.75px]">1,200 hours</p>
                        <Heading size="h3" className="!leading-[30px] !tracking-[-0.25px] text-gray-200">
                            Estimated annual time savings
                        </Heading>
                    </div>
                    <div>
                        <Link
                            href="https://sourcegraph.com/case-studies/how-sourcegraph-transformed-nine-development-workflow"
                            title="Case study"
                            className="btn p-0 text-left  font-semibold !-tracking-[0.25px] text-white hover:underline  md:border-none  md:text-center "
                        >
                            Read the case study
                            <ChevronRightIcon className="!mb-0 ml-[10px] inline" />
                        </Link>
                    </div>
                </div>
            </ContentSection>
            <ContentSection
                className="flex flex-col py-0 md:gap-10"
                parentClassName="!py-0 md:!pt-[112px] !pt-8 md:px-[80px]"
            >
                <div className="flex flex-col gap-6 md:flex-row">
                    <div className="flex basis-1/3 flex-col gap-6 p-10">
                        <img src="enterprise/security-brand-icon.svg" className="w-[51px]" alt="" />
                        <Heading size="h2" className="!text-[52px] !leading-[62px] !tracking-[-1px]">
                            Secure
                        </Heading>
                    </div>
                    {enterpriseCardObjects.slice(0, 2).map(({ heading, paragraph }) => (
                        <EnterpriseCard key={heading} heading={heading} paragraph={paragraph} />
                    ))}
                </div>
                <div className="flex flex-col gap-6 md:flex-row md:gap-0">
                    {enterpriseCardObjects.slice(2).map(({ heading, paragraph }) => (
                        <EnterpriseCard key={heading} heading={heading} paragraph={paragraph} />
                    ))}
                </div>
            </ContentSection>
            <ContentSection
                className="flex max-w-[1232px] flex-col gap-6 md:flex-row"
                parentClassName="md:px-[80px] !py-0 md:!py-10"
            >
                <div className=" flex justify-center rounded-2xl border-1 border-gray-200 py-16 px-6 md:!w-[417px] md:px-20">
                    <div className="flex !w-[278px] flex-col gap-16">
                        <div>
                            <p className="mb-4 font-sans text-[75px] font-semibold leading-[62px] tracking-[-1px]">
                                &lt;5 minutes
                            </p>
                            <Heading size="h3" className="!leading-[30px] !tracking-[-0.25px]">
                                Time to find and fix instances of a vulnerability
                            </Heading>
                        </div>
                        <div>
                            <p className="mb-4  font-sans text-[75px] font-semibold leading-[62px] tracking-[-1px]">
                                &lt;4 days
                            </p>
                            <Heading size="h3" className="!leading-[30px] !tracking-[-0.25px]">
                                Time to deliver Log4j vulnerability patches to customers
                            </Heading>
                        </div>
                    </div>
                </div>
                <div className="flex flex-row items-center rounded-2xl border-1 border-gray-200 bg-white py-16 px-6 md:items-end md:px-20 ">
                    <div>
                        <img src="enterprise/nutanix.svg" alt="" className="mb-6 w-[180px]" />
                        <p className="mb-16 text-[35px] font-normal leading-[43.75px] -tracking-[0.25px]">
                            Nutanix was able to find every instance of Log4j vulnerabilities in their large codebase and
                            ship codebase-wide fixes in less than a week
                        </p>
                        <div className="text-right">
                            <Link
                                href="https://sourcegraph.com/case-studies/nutanix-fixed-log4j-with-sourcegraph"
                                title="Case study"
                                className="btn flex-end p-0 text-center text-right font-semibold !-tracking-[0.25px] text-violet-500 hover:underline  md:mx-0 md:border-none  md:text-left "
                            >
                                Read the case study
                                <ChevronRightIcon className="!mb-0 ml-[10px] inline" />
                            </Link>
                        </div>
                    </div>
                </div>
            </ContentSection>
            <ContentSection
                className="flex flex-col gap-6 md:flex-row"
                parentClassName="!py-0 md:!pb-[96px] !pb-[64px] md:px-[80px]"
            >
                {securityFeatures.map((feature, index) => (
                    <SecurityFeature className="max-w-[410px]" key={index} {...feature} />
                ))}
            </ContentSection>
            <ContentSection
                className="max-w-[1232px] rounded-2xl border-1 border-gray-200 bg-white py-16 px-6 md:px-10"
                parentClassName="!py-0 md:px-[80px]"
            >
                <Heading size="h6" className="mb-4">
                    cody
                </Heading>
                <Heading size="h2" className="mb-10 !leading-10 !tracking-[-1px]">
                    Enterprise-grade AI security and governance
                </Heading>
                <div className="mb-6 grid grid-cols-1 gap-6 md:grid-cols-3 ">
                    {securityCardFeatures.map((feature, index) => (
                        <SecurityCard key={index} {...feature} />
                    ))}
                </div>
                <div className="grid grid-cols-1 gap-6 md:grid-cols-3">
                    <div className="col-span-1 flex flex-col-reverse justify-between gap-x-[33px] gap-y-4 rounded-2xl border-1 border-gray-200 md:col-span-2 md:flex-row md:items-end ">
                        <div className="pr-10 md:pr-0">
                            <img alt="" src="/enterprise/screenshot.svg" className="rounded-bl-lg" />
                        </div>
                        <div className="mt-10 mb-4 pl-10 pt-10 pr-10 md:my-10  md:py-10   md:pl-0 md:pb-10">
                            <div className="flex max-w-[311px] flex-col gap-4">
                                <Heading size="h2" className="!leading-10 !tracking-[-1px]">
                                    Guardrails to catch licensed code
                                </Heading>
                                <p className="mb-0 text-[18px] font-normal leading-[27px] -tracking-[0.25px]">
                                    Sourcegraph automatically checks AI suggestions against open source code and highlights
                                    matches to mitigate IP risk.
                                </p>
                            </div>
                        </div>
                    </div>
                    <div className="flex flex-col gap-6">
                        <SecurityCard
                            icon={<MdLock size={24} />}
                            heading="No model training with your data"
                            paragraph="We do not train models using data from Cody Enterprise users, so your code stays private
                                to you."
                        />
                        <div className="flex items-start gap-4 rounded-2xl border-1 border-gray-200 bg-gray-100 py-10 px-8">
                            <img src="/enterprise/file-document-outline.svg" alt="" />
                            <Heading size="h5" className="!font-[590px] !leading-[25px] !tracking-[-0.25px]">
                                To learn more, read our
                                <Link
                                    href="/whitepapers/cody-security-and-legal"
                                    title="Cody security & legal whitepaper"
                                    className="mx-[3px] text-black underline underline-offset-[4.3px] "
                                >
                                    Cody security & legal whitepaper
                                </Link>
                            </Heading>
                        </div>
                    </div>
                </div>
            </ContentSection>

            <ContentSection
                className="flex max-w-[1232px] flex-col justify-between gap-6 rounded-2xl border-1 border-gray-200 bg-violet-700 py-16 px-6 md:px-[56px]"
                parentClassName="md:px-[80px] !py-[96px]"
            >
                <Heading size="h2" className="!leading-10 !tracking-[-1px] text-white">
                    Contact us for a demo or to start an enterprise trial
                </Heading>
                <div className="text-center md:items-center">
                    <div className="mx-auto flex max-w-[300px] sm:max-w-full  sm:w-full flex-col items-center gap-6 sm:flex-row md:!w-auto md:gap-4">
                        <Link
                            className="btn btn-inverted-primary w-full sm:w-[140px] bg-white  md:w-auto"
                            href="/contact/request-info"
                            title="Contact us"
                            data-button-style={buttonStyle.primary}
                            data-button-location={buttonLocation} 
                            data-button-type="cta"
                        >
                            Contact us
                        </Link>
                        <Link
                            className="btn w-full sm:w-[140px] items-center text-white outline  md:w-auto"
                            href="/pricing"
                            title="See Pricing"
                            data-button-style={buttonStyle.outline}
                            data-button-location={buttonLocation.hero}
                            data-button-type="cta"
                        >
                            See pricing
                        </Link>
                    </div>
                </div>
            </ContentSection>
        </Layout>
    )
}

const EnterpriseIcon: FunctionComponent<{ src: string; alt: string; className?: string }> = ({
    src,
    alt,
    className,
}) => (
    <div className={classNames(className)}>
        <img className="max-h-full max-w-full" alt={alt} src={src} />
    </div>
)

const EnterpriseCard: FunctionComponent<{ heading: string; paragraph: string }> = ({ heading, paragraph }) => (
    <div className="flex basis-1/3 flex-col gap-4 p-10">
        <Heading size="h4" className="!leading-[30px] !tracking-[-0.25px]">
            {heading}
        </Heading>
        <p className="mb-0 text-[18px] font-normal leading-[27px] -tracking-[0.25px]">{paragraph}</p>
    </div>
)

const SecurityFeature: FunctionComponent<{
    imgSrc: string[]
    altText: string
    heading: string
    paragraph: string | ReactNode
    className?: string
}> = ({ imgSrc, altText, heading, paragraph, className }) => (
    <div className={classNames('p-10', className)}>
        <div className="flex flex-row gap-10">
            {imgSrc.map(src => (
                <img key={altText} src={src} alt={altText} className="mb-8 h-[60px] w-[60px]" />
            ))}
        </div>
        <Heading size="h4">{heading}</Heading>
        <p className="mb-0 mt-4 text-[18px] font-normal leading-[27px] -tracking-[0.25px]">{paragraph}</p>
    </div>
)

const SecurityCard: FunctionComponent<{ icon: ReactNode; heading: string; paragraph: string }> = ({
    icon,
    heading,
    paragraph,
}) => (
    <div className="flex flex-col gap-4 rounded-2xl border-1 border-gray-200 py-10 px-8">
        {icon}
        <Heading size="h4" className="font-sf !leading-[30px] tracking-[-0.25]">
            {heading}
        </Heading>
        <p className="mb-0 text-[18px] font-normal leading-[27px] -tracking-[0.25px]">{paragraph}</p>
    </div>
)

export default Enterprise
