import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => (
    <>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <div>about replatform</div>
    </>
)

export default Home
