name: Skip Approval

on:
  pull_request:
    types: opened
    branches:
      - main

    # Glob paths to dismiss PR approvals
    paths:
      - 'docs/**/*'
      - 'blogposts/**/*'

jobs:
  approve:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl --request POST \
          --url https://api.github.com/repos/${{github.repository}}/pulls/${{github.event.number}}/reviews \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          -d '{"event":"APPROVE"}'
