# This ensures our end to end tests run for production builds
name: Check Links

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.15.0'
      - name: Install dependencies
        run: yarn ci
      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.5.1
        with:
          fail: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
