# This ensures our end to end tests run for production builds
name: E2E Tests

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main

jobs:
  approve:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: package.json
      - uses: pnpm/action-setup@v2
        with:
          run_install: true
      - name: Run E2E Tests
        run: pnpm run test:ci
